# Imaging protocols available in Fusion
protocols: 
  - 'Hello world'
  - 'Goodbye World'



#Fluid settings
system volume: 200
buffer:
  Stripping Solution: 
    m: 0.11599561
    b: -0.0142795
  PBST Short: 
    m: 0.11599561
    b: -0.0142795
  PBS:
    m: 0.11599561
    b: -0.0142795
  Hybridization: 
    m: 0.11599561
    b: -0.0142795
  Ligation Buffer: 
    m: 0.11599561
    b: -0.0142795
  Ligation Solution:
    m: 0.11599561
    b: -0.0142795
  PBST Long: 
    m: 0.11599561
    b: -0.0142795
  Imaging Buffer: 
    m: 0.11599561
    b: -0.0142795
optimal volume:
    m: 0.11599561
    b: -0.0142795

speeds:
- 5
- 15 
- 23


time between stages: 1
shaker duration: 0.075

skip stages:
  Stripping Solution: 1
  PBST Short: 1
  PBS: 1
  Hybridization: 1
  Ligation Buffer: 1
  Ligation Solution: 1
  PBST Long: 1 
  Imaging Buffer: 1 



stage durations:
  Stripping Solution: 1
  PBST Short: 1
  PBS: 1
  Hybridization: 1
  Ligation Buffer: 1
  Ligation Solution: 1
  PBST Long: 1 
  Imaging Buffer: 1


#Serial Devices
pump port: '/dev/ttyUSB3'
mvp port: '/dev/ttyUSB2'
shaker port: '/dev/ttyACM0'

