# Imaging protocols available in Fusion
protocols: 
  - 'Hello world'
  - 'Goodbye World'



#Fluid settings
system volume: 200
buffer:
  tdt_pre:
    speed: 2 
    m: 0.11599561
    b: -0.0142795
  tdt_react:
    speed: 2 
    m: 0.11599561
    b: -0.0142795
  pbs:
    speed: 2
    m: 0.11599561
    b: -0.0142795
  hybridization: 
    speed: 2
    m: 0.11599561
    b: -0.0142795
  ssc:
    speed: 2 
    m: 0.11599561
    b: -0.0142795
  pr2:
    speed: 2
    m: 0.11599561
    b: -0.0142795
  iss: 
    speed: 2
    m: 0.11599561
    b: -0.0142795
  imaging: 
    speed: 2
    m: 0.11599561
    b: -0.0142795
  zw_pr:
    speed: 2 
    m: 0.11599561
    b: -0.0142795
  cleavage: 
    speed: 2
    m: 0.11599561
    b: -0.0142795
  dapi:
    speed: 2 
    m: 0.11599561
    b: -0.0142795
optimal volume:
    m: 0.11599561
    b: -0.0142795

speeds:
- 5
- 15 
- 23


time between stages: 1
shaker duration: 0.075

skip stages:
  tdt_pre: 1
  tdt_react: 1
  pbs: 1
  hybridization: 1
  ssc: 1
  pr2: 1
  iss: 1 
  imaging: 1 
  zw_pr: 1
  cleavage: 1
  dapi: 1 




stage durations:
  tdt_pre: 1
  tdt_react: 1
  pbs: 1
  hybridization: 1
  ssc: 1
  pr2: 1
  iss: 1 
  imaging: 1 
  zw_pr: 1
  cleavage: 1
  dapi: 1 


#Serial Devices
pump port: '/dev/ttyUSB3'
mvp port: '/dev/ttyUSB2'
shaker port: '/dev/ttyACM0'

